name: .NET Core

on:
  issue_comment:
    types: [created, edited]
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: | 
           dotnet nuget add source https://nuget-test.devexpress.com/api -n DXFeed -u myUsername -p ${{ secrets.MYNUGETFEED }} --store-password-in-clear-text --valid-authentication-types basic, negotiate
           dotnet restore --ignore-failed-sources ./CS/Example.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore ./CS/Example.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./CS/Example.sln
